package dima.introspectionbasedagents.kernel;

import dima.introspectionbasedagents.services.communicating.AsynchronousCommunicationComponent;

public interface CommunicatingCompetentComponent extends CompetentComponent, AsynchronousCommunicationComponent {

}
